// ============================================
// DEV-X PRO - Professional Developer Suite
// Developer: @Mrddev | Telegram: @devxtechzone
// ============================================

const express = require('express');
const mongoose = require('mongoose');
const archiver = require('archiver');
const axios = require('axios');
const cors = require('cors');
const multer = require('multer');
const { v4: uuidv4 } = require('uuid');
const path = require('path');
const fs = require('fs');
require('dotenv').config();

const app = express();

app.use(cors());
app.use(express.json({ limit: '100mb' }));
app.use(express.urlencoded({ extended: true, limit: '100mb' }));

// File upload
const storage = multer.diskStorage({
    destination: (req, file, cb) => cb(null, 'uploads/'),
    filename: (req, file, cb) => cb(null, `${Date.now()}-${file.originalname}`)
});
const upload = multer({ storage, limits: { fileSize: 50 * 1024 * 1024 } });

if (!fs.existsSync('uploads')) fs.mkdirSync('uploads');

// MongoDB
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb+srv://mrdev:dev091339@cluster0.grjlq7v.mongodb.net/devx_pro';
mongoose.connect(MONGODB_URI).then(() => console.log('✅ MongoDB connected'));

// Schemas
const ProjectSchema = new mongoose.Schema({
    projectId: String, userId: String, toolType: String, title: String,
    files: Object, uploadedFiles: Array, downloadCount: { type: Number, default: 0 },
    createdAt: { type: Date, default: Date.now }
});
const SessionSchema = new mongoose.Schema({
    sessionId: String, toolType: String, description: String, generatedCode: Object,
    uploadedFiles: Array, status: String, createdAt: { type: Date, default: Date.now, expires: 3600 }
});

const Project = mongoose.model('Project', ProjectSchema);
const Session = mongoose.model('Session', SessionSchema);

// AI Engine
const AI_API_URL = process.env.AI_API_URL || 'https://api.dev-x.com/v1/chat/completions';
const AI_API_KEY = process.env.AI_API_KEY || 'devx-k9v41ybg64exej9lkkovg5dof00ep3yr';

async function callAI(prompt) {
    try {
        const response = await axios.post(AI_API_URL, {
            model: "llama-3.3-70b",
            messages: [{ role: "user", content: prompt }],
            temperature: 0.7,
            max_tokens: 4000
        }, { headers: { 'Authorization': `Bearer ${AI_API_KEY}` } });
        return response.data.choices[0].message.content;
    } catch (error) {
        return null;
    }
}

function generateFallback(toolType, description) {
    return {
        title: `${toolType}`,
        files: {
            "index.html": `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${toolType} | Dev-X</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            background: #0a0a0f;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            color: #e2e2e2;
            line-height: 1.6;
        }
        .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }
        header { border-bottom: 1px solid #1e1e2a; padding-bottom: 1rem; margin-bottom: 2rem; }
        h1 { font-size: 1.8rem; font-weight: 600; color: #fff; }
        .btn {
            background: #2d2d3a;
            border: none;
            padding: 0.6rem 1.2rem;
            border-radius: 6px;
            color: #fff;
            cursor: pointer;
            font-size: 0.9rem;
        }
        .btn-primary { background: #3b82f6; }
        footer {
            border-top: 1px solid #1e1e2a;
            margin-top: 3rem;
            padding-top: 1rem;
            text-align: center;
            font-size: 0.8rem;
            color: #6b7280;
        }
        a { color: #3b82f6; text-decoration: none; }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>${toolType}</h1>
        </header>
        <main>
            <p>${description || 'Professional solution generated by Dev-X Pro.'}</p>
            <button class="btn btn-primary" onclick="alert('Ready')">Launch</button>
        </main>
        <footer>
            <p>Dev-X Pro | <a href="https://t.me/devxtechzone">@devxtechzone</a></p>
        </footer>
    </div>
</body>
</html>`
        },
        instructions: "Open index.html in browser"
    };
}

// API Routes
app.get('/api/tools', (req, res) => {
    res.json([
        "React App", "Node.js API", "Telegram Bot", "Discord Bot", 
        "Chrome Extension", "Web Scraper", "Admin Dashboard", "Portfolio",
        "E-commerce", "Landing Page", "REST API", "GraphQL API",
        "WhatsApp Bot", "VS Code Extension", "Python Script", "CLI Tool"
    ]);
});

app.post('/api/upload/:sessionId', upload.array('files', 20), async (req, res) => {
    const { sessionId } = req.params;
    const uploadedFiles = req.files.map(f => ({ originalname: f.originalname, filename: f.filename, path: f.path, size: f.size }));
    
    let session = await Session.findOne({ sessionId });
    if (session) {
        session.uploadedFiles = [...(session.uploadedFiles || []), ...uploadedFiles];
        await session.save();
    } else {
        const newSession = new Session({ sessionId, uploadedFiles, status: 'uploading' });
        await newSession.save();
    }
    res.json({ success: true, files: uploadedFiles });
});

app.post('/api/generate', async (req, res) => {
    const { toolType, description, userId, sessionId } = req.body;
    const finalSessionId = sessionId || uuidv4();
    
    if (!toolType || !description) {
        return res.status(400).json({ error: "Tool type and description required" });
    }
    
    try {
        let session = await Session.findOne({ sessionId: finalSessionId });
        const uploadedFiles = session?.uploadedFiles || [];
        
        const generated = generateFallback(toolType, description);
        
        if (!session) {
            session = new Session({ sessionId: finalSessionId, toolType, description, generatedCode: generated, uploadedFiles, status: 'completed' });
        } else {
            session.toolType = toolType;
            session.description = description;
            session.generatedCode = generated;
            session.status = 'completed';
        }
        await session.save();
        
        const project = new Project({ projectId: finalSessionId, userId: userId || 'anonymous', toolType, title: generated.title, files: generated, uploadedFiles });
        await project.save();
        
        res.json({ success: true, sessionId: finalSessionId, project: generated });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

app.get('/api/download/:sessionId', async (req, res) => {
    const session = await Session.findOne({ sessionId: req.params.sessionId });
    if (!session || !session.generatedCode) {
        return res.status(404).json({ error: "Project not found" });
    }
    
    const archive = archiver('zip', { zlib: { level: 9 } });
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename=devx-${session.toolType?.replace(/ /g, '-')}.zip`);
    archive.pipe(res);
    
    const files = session.generatedCode.files || {};
    for (const [filename, content] of Object.entries(files)) {
        archive.append(content, { name: filename });
    }
    
    if (session.uploadedFiles && session.uploadedFiles.length > 0) {
        for (const file of session.uploadedFiles) {
            const filePath = path.join(__dirname, 'uploads', file.filename);
            if (fs.existsSync(filePath)) {
                archive.file(filePath, { name: `assets/${file.originalname}` });
            }
        }
    }
    
    await archive.finalize();
    await Project.updateOne({ projectId: req.params.sessionId }, { $inc: { downloadCount: 1 } });
});

// Frontend
app.get('/', (req, res) => {
    res.send(`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dev-X Pro | Developer Suite</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            background: #09090b;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Inter', Roboto, sans-serif;
            color: #e4e4e7;
            line-height: 1.5;
        }
        
        /* Layout */
        .app {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }
        
        .container {
            max-width: 1280px;
            margin: 0 auto;
            padding: 0 1.5rem;
            width: 100%;
        }
        
        /* Header */
        .header {
            border-bottom: 1px solid #27272a;
            padding: 1rem 0;
            background: #09090b/80;
            backdrop-filter: blur(8px);
            position: sticky;
            top: 0;
            z-index: 10;
        }
        
        .header-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
        .logo h1 {
            font-size: 1.25rem;
            font-weight: 600;
            letter-spacing: -0.01em;
        }
        
        .logo span {
            color: #3b82f6;
        }
        
        .logo p {
            font-size: 0.75rem;
            color: #71717a;
        }
        
        .social-links {
            display: flex;
            gap: 1rem;
        }
        
        .social-links a {
            color: #71717a;
            text-decoration: none;
            font-size: 0.875rem;
            transition: color 0.2s;
        }
        
        .social-links a:hover {
            color: #3b82f6;
        }
        
        /* Main */
        .main {
            flex: 1;
            padding: 2rem 0;
        }
        
        /* Tools Grid */
        .tools-section {
            margin-bottom: 2rem;
        }
        
        .section-title {
            font-size: 0.875rem;
            font-weight: 500;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: #71717a;
            margin-bottom: 1rem;
        }
        
        .tools-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
            gap: 0.5rem;
        }
        
        .tool-btn {
            background: #18181b;
            border: 1px solid #27272a;
            border-radius: 0.5rem;
            padding: 0.625rem 1rem;
            font-size: 0.875rem;
            font-weight: 500;
            color: #e4e4e7;
            cursor: pointer;
            transition: all 0.2s;
            text-align: left;
        }
        
        .tool-btn:hover {
            background: #27272a;
            border-color: #3b82f6;
        }
        
        .tool-btn.active {
            background: #3b82f6;
            border-color: #3b82f6;
            color: white;
        }
        
        /* Cards */
        .card {
            background: #18181b;
            border: 1px solid #27272a;
            border-radius: 0.75rem;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
        }
        
        .card-title {
            font-size: 1rem;
            font-weight: 600;
            margin-bottom: 1rem;
        }
        
        /* Upload Area */
        .upload-area {
            border: 1px dashed #3b3b40;
            border-radius: 0.5rem;
            padding: 1.5rem;
            text-align: center;
            cursor: pointer;
            transition: all 0.2s;
            margin-bottom: 1rem;
        }
        
        .upload-area:hover {
            border-color: #3b82f6;
            background: #27272a/30;
        }
        
        .file-list {
            margin-top: 0.75rem;
            font-size: 0.75rem;
            color: #71717a;
        }
        
        /* Form */
        textarea {
            width: 100%;
            background: #09090b;
            border: 1px solid #27272a;
            border-radius: 0.5rem;
            padding: 0.75rem;
            color: #e4e4e7;
            font-size: 0.875rem;
            font-family: inherit;
            resize: vertical;
            margin-bottom: 1rem;
        }
        
        textarea:focus {
            outline: none;
            border-color: #3b82f6;
        }
        
        /* Buttons */
        .btn {
            border: none;
            border-radius: 0.5rem;
            padding: 0.625rem 1.25rem;
            font-size: 0.875rem;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.2s;
        }
        
        .btn-primary {
            background: #3b82f6;
            color: white;
        }
        
        .btn-primary:hover {
            background: #2563eb;
        }
        
        .btn-secondary {
            background: #27272a;
            color: #e4e4e7;
        }
        
        .btn-secondary:hover {
            background: #3b3b40;
        }
        
        .btn-group {
            display: flex;
            gap: 0.75rem;
            margin-top: 1rem;
        }
        
        /* Result */
        .result-card {
            display: none;
        }
        
        .result-card.show {
            display: block;
            animation: fadeIn 0.3s ease;
        }
        
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }
        
        .code-preview {
            background: #09090b;
            border: 1px solid #27272a;
            border-radius: 0.5rem;
            padding: 1rem;
            font-family: 'Monaco', 'Menlo', monospace;
            font-size: 0.75rem;
            overflow-x: auto;
            margin: 1rem 0;
        }
        
        /* Footer */
        .footer {
            border-top: 1px solid #27272a;
            padding: 1.5rem 0;
            text-align: center;
            font-size: 0.75rem;
            color: #71717a;
        }
        
        /* Loading Overlay */
        .loading-overlay {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: rgba(9, 9, 11, 0.95);
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 1000;
            display: none;
        }
        
        .loading-overlay.show {
            display: flex;
        }
        
        .spinner {
            width: 40px;
            height: 40px;
            border: 2px solid #27272a;
            border-top-color: #3b82f6;
            border-radius: 50%;
            animation: spin 0.8s linear infinite;
        }
        
        @keyframes spin {
            to { transform: rotate(360deg); }
        }
        
        /* Responsive */
        @media (max-width: 768px) {
            .container { padding: 0 1rem; }
            .tools-grid { grid-template-columns: repeat(auto-fill, minmax(120px, 1fr)); }
        }
    </style>
</head>
<body>
    <div class="app">
        <header class="header">
            <div class="container">
                <div class="header-content">
                    <div class="logo">
                        <h1>DEV-X <span>PRO</span></h1>
                        <p>developer suite</p>
                    </div>
                    <div class="social-links">
                        <a href="https://t.me/devxtechzone" target="_blank">Telegram</a>
                        <a href="https://whatsapp.com/channel/0029VbC55M1EKyZCBwpsd035" target="_blank">WhatsApp</a>
                    </div>
                </div>
            </div>
        </header>
        
        <main class="main">
            <div class="container">
                <div class="tools-section">
                    <div class="section-title">Development Tools</div>
                    <div class="tools-grid" id="toolsGrid"></div>
                </div>
                
                <div class="card">
                    <div class="card-title">Assets</div>
                    <div class="upload-area" id="uploadArea">
                        <div>📁 Drop files or click to upload</div>
                        <div class="file-list" id="fileList"></div>
                        <input type="file" id="fileInput" multiple style="display:none">
                    </div>
                </div>
                
                <div class="card">
                    <div class="card-title">Project Description</div>
                    <textarea id="description" rows="4" placeholder="Describe what you want to build...&#10;&#10;Example: A REST API with user authentication and database integration"></textarea>
                    <button class="btn btn-primary" id="generateBtn">Generate Project</button>
                </div>
                
                <div class="result-card" id="resultCard">
                    <div class="card">
                        <div class="card-title" id="resultTitle"></div>
                        <div id="resultContent"></div>
                        <div class="btn-group">
                            <button class="btn btn-primary" id="downloadBtn">Download ZIP</button>
                            <button class="btn btn-secondary" id="resetBtn">New Project</button>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        
        <footer class="footer">
            <div class="container">
                <p>Dev-X Pro | @Mrddev</p>
            </div>
        </footer>
    </div>
    
    <div class="loading-overlay" id="loadingOverlay">
        <div class="spinner"></div>
    </div>
    
    <script>
        let currentSessionId = null;
        let selectedTool = "React App";
        let uploadedFiles = [];
        
        const tools = [
            "React App", "Node.js API", "Telegram Bot", "Discord Bot",
            "Chrome Extension", "Web Scraper", "Admin Dashboard", "Portfolio",
            "E-commerce", "Landing Page", "REST API", "GraphQL API",
            "WhatsApp Bot", "Python Script", "CLI Tool", "VS Code Extension"
        ];
        
        // Render tools
        const toolsGrid = document.getElementById('toolsGrid');
        tools.forEach(tool => {
            const btn = document.createElement('button');
            btn.className = 'tool-btn' + (tool === selectedTool ? ' active' : '');
            btn.textContent = tool;
            btn.onclick = () => {
                document.querySelectorAll('.tool-btn').forEach(b => b.classList.remove('active'));
                btn.classList.add('active');
                selectedTool = tool;
            };
            toolsGrid.appendChild(btn);
        });
        
        // File upload
        const uploadArea = document.getElementById('uploadArea');
        const fileInput = document.getElementById('fileInput');
        
        uploadArea.onclick = () => fileInput.click();
        uploadArea.ondragover = (e) => { e.preventDefault(); uploadArea.style.borderColor = '#3b82f6'; };
        uploadArea.ondragleave = () => uploadArea.style.borderColor = '#3b3b40';
        uploadArea.ondrop = async (e) => {
            e.preventDefault();
            uploadArea.style.borderColor = '#3b3b40';
            const files = Array.from(e.dataTransfer.files);
            await uploadFiles(files);
        };
        
        fileInput.onchange = async (e) => await uploadFiles(Array.from(e.target.files));
        
        async function uploadFiles(files) {
            if (!currentSessionId) currentSessionId = 'session_' + Date.now();
            
            const formData = new FormData();
            files.forEach(f => formData.append('files', f));
            
            const response = await fetch(\`/api/upload/\${currentSessionId}\`, {
                method: 'POST',
                body: formData
            });
            const data = await response.json();
            uploadedFiles.push(...data.files);
            
            const fileListDiv = document.getElementById('fileList');
            fileListDiv.innerHTML = uploadedFiles.map(f => \`📄 \${f.originalname}\`).join('<br>');
        }
        
        // Generate
        async function generate() {
            const description = document.getElementById('description').value.trim();
            if (!description) {
                alert('Please describe your project');
                return;
            }
            
            const btn = document.getElementById('generateBtn');
            const overlay = document.getElementById('loadingOverlay');
            
            btn.disabled = true;
            btn.textContent = 'Generating...';
            overlay.classList.add('show');
            
            try {
                const response = await fetch('/api/generate', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        toolType: selectedTool,
                        description: description,
                        userId: 'user_' + Date.now(),
                        sessionId: currentSessionId
                    })
                });
                
                const data = await response.json();
                
                if (data.success) {
                    currentSessionId = data.sessionId;
                    const files = data.project.files || {};
                    
                    document.getElementById('resultTitle').textContent = \`\${selectedTool} - Ready\`;
                    document.getElementById('resultContent').innerHTML = \`
                        <div class="code-preview">
                            <strong>Files generated:</strong> \${Object.keys(files).join(', ')}
                        </div>
                        <p style="font-size:0.875rem; color:#71717a;">\${data.project.instructions || 'Download the ZIP file to get started.'}</p>
                    \`;
                    document.getElementById('resultCard').classList.add('show');
                    window.scrollTo({ top: document.getElementById('resultCard').offsetTop - 100, behavior: 'smooth' });
                } else {
                    alert('Error: ' + data.error);
                }
            } catch (error) {
                alert('Error: ' + error.message);
            } finally {
                btn.disabled = false;
                btn.textContent = 'Generate Project';
                overlay.classList.remove('show');
            }
        }
        
        function downloadProject() {
            if (currentSessionId) {
                window.location.href = \`/api/download/\${currentSessionId}\`;
            }
        }
        
        function resetForm() {
            document.getElementById('description').value = '';
            document.getElementById('resultCard').classList.remove('show');
            uploadedFiles = [];
            document.getElementById('fileList').innerHTML = '';
            currentSessionId = null;
        }
        
        document.getElementById('generateBtn').onclick = generate;
        document.getElementById('downloadBtn').onclick = downloadProject;
        document.getElementById('resetBtn').onclick = resetForm;
    </script>
</body>
</html>
    `);
});

// Start server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`\n✅ Dev-X Pro running at http://localhost:${PORT}\n`);
    console.log(`👨‍💻 Developer: @Mrddev`);
    console.log(`📱 Telegram: @devxtechzone\n`);
});
